### ISSUE TITLE
Write bool value failed

### ISSUE THREAD

**Issue by Ri0nGo** [REQUEA/bacnet#2]
This is my send WriteProperty,

```
	wp := service.WriteProperty{
		ObjectID: bacnet.ObjectID{
			Type:     bacnet.BinaryOutput,
			Instance: bacnet.ObjectInstance(object_id),
		},
		Property: bacnet.PropertyIdentifier{
			Type: bacnet.PresentValue,
		},
		PropertyValue: bacnet.PropertyValue{
			Type:  bacnet.PresentValueBoolean,
			Value: true,
		},
		Priority: 0,
	}

// wp  => {{BinaryOutput 0} {PresentValue <nil>} {1 true} PriorityList(0)}
```

An error occurred throught use client.WriteProperty(ctx, addr, wp)  function

```
apdu error class PropertyError code InvalidDataType
```
Is there a problem with my wp setup？

Looking forward to your reply.

**Comment by aureliar8** [comment]
It's been a long time since I worked on this code, but I'm a but confused by your question. 

Because this lib doesn't export a `bacnet.PresentValueBoolean` symbol nor a `WriteProperty` method on the client. 
Also the type of PropertyValue.Value is a uint32 while your snippet tries to use a boolean. 

Could you provide a runnable test code that exhibit the error ?

**Comment by Ri0nGo** [comment]
> It's been a long time since I worked on this code, but I'm a but confused by your question.
> 
> Because this lib doesn't export a `bacnet.PresentValueBoolean` symbol nor a `WriteProperty` method on the client. Also the type of PropertyValue.Value is a uint32 while your snippet tries to use a boolean.
> 
> Could you provide a runnable test code that exhibit the error ?

Thanks your reply, These methods are modified. That's why I can use them.  

I use wireshark find, For BI, BO, BV types you should enter PresentValueEnumerated (PropertyValue.type filed).  Then can write the values normally. 

Thank you very much for this repo, help me to collect bacnet protocal data.

**Comment by YiuTerran** [comment]
@Ri0nGo  Hello, can you share your modified code?  I can't find a usable library for GoLang.

大兄弟，江湖救急，能不能分享一下代码？github上没找到好用的BACnet读写库，只有这个项目能跑通read逻辑，但是缺write。

**Comment by Ri0nGo** [comment]
> [@Ri0nGo](https://github.com/Ri0nGo) Hello, can you share your modified code? I can't find a usable library for GoLang.
> 
> 大兄弟，江湖救急，能不能分享一下代码？github上没找到好用的BACnet读写库，只有这个项目能跑通read逻辑，但是缺write。

兄弟，公司代码不能分享，核心代码在这里
https://github.com/REQUEA/bacnet/blob/25d832fb4b2306c17d492f66287f862fec1d43e8/bacip/client.go#L294C1-L309C2
```
func (c *Client) send(npdu NPDU) (int, error) {
	bytes, err := BVLC{
		Type:     TypeBacnetIP,
		Function: BacFuncUnicast,
		NPDU:     npdu,
	}.MarshalBinary()
	if err != nil {
		return 0, err
	}
	if npdu.Destination == nil {
		return 0, fmt.Errorf("destination bacnet address should be not nil to send unicast")
	}
	addr := bacnet.UDPFromAddress(*npdu.Destination)
	return c.udp.WriteToUDP(bytes, &addr)


}
```

**Comment by YiuTerran** [comment]
I just sent a PR to support `WriteProperty`.
